services:
  web:
    image: nginx
    volumes:
    - ./ext:/var/www/
    - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
    - "8081:80"
    command: [nginx-debug, '-g', 'daemon off;']
    networks:
      - logging-network
  backend:
    image: node:16
    volumes:
    - ./backend:/app
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: on-failure
    networks:
      - logging-network
networks:
  logging-network:
    driver: bridge